_wandb:
    value:
        cli_version: 0.21.4
        e:
            id2fmuy9fd8bs66zcve1pn2ko85amdit:
                args:
                    - --p
                    - "97"
                    - --train_fraction
                    - "0.2"
                    - --weight_decay
                    - "0.1"
                    - --batch_size
                    - "1881"
                    - --no_shuffle
                    - --lr
                    - "1e-3"
                    - --max_steps
                    - "30000"
                    - --eval_every
                    - "1000"
                    - --auto_lr_decay
                    - --stop_after_grok
                    - "10000"
                    - --output_dir
                    - runs/grokking_final
                    - --wandb
                    - --save_activations
                    - --activation_save_every
                    - "1000"
                codePath: grokking\grok_clean.py
                codePathLocal: grokking\grok_clean.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1999379623936"
                        used: "1870537101312"
                email: aneesh.kumar6214@gmail.com
                executable: C:\Users\anees\OneDrive\Desktop\Algoverse\.venv\Scripts\python.exe
                git:
                    commit: e9c9fec893759cdf79fca797f8e4d1e7e4e7646b
                    remote: https://github.com/aneesh6214/nyx-soso-predicting-emergence.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-30b6d14e-6a07-903e-7a08-f7e44faaad46
                host: aang-desktop
                memory:
                    total: "67814113280"
                os: Windows-10-10.0.22631-SP0
                program: C:\Users\anees\OneDrive\Desktop\Algoverse\grokking\grok_clean.py
                python: CPython 3.10.0
                root: C:\Users\anees\OneDrive\Desktop\Algoverse
                startedAt: "2025-09-30T01:06:27.486634Z"
                writerId: id2fmuy9fd8bs66zcve1pn2ko85amdit
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.21.4
            "8":
                - 3
            "12": 0.21.4
            "13": windows-amd64
activation_save_every:
    value: 1000
auto_lr_decay:
    value: true
batch_size:
    value: 1881
d_ff:
    value: 256
d_model:
    value: 128
eval_every:
    value: 1000
lr:
    value: 0.001
lr_decay_factor:
    value: 0.1
lr_decay_step:
    value: 0
max_steps:
    value: 30000
n_heads:
    value: 4
n_layers:
    value: 2
no_shuffle:
    value: true
output_dir:
    value: runs/grokking_final
p:
    value: 97
save_activations:
    value: true
seed:
    value: 42
stop_after_grok:
    value: 10000
train_fraction:
    value: 0.2
wandb:
    value: true
weight_decay:
    value: 0.1
